server:
  port: 8888
logging:
  path: logs
  file: userManger.log
spring:
  application:
    name: userManger
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/user?serverTimezone=GMT
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
  - mapper/*
